# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Staringit' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Staringit

  pod 'Firebase/Messaging'
  pod 'Firebase/Core'




end
